appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: lxskgzqnCxnuONE/qHTLrBNRQGvpRAFzKqkC2rC1Q8xswjPkC79YE1ZEg3elLGMCZG+sTrS1zxc2Wc8W9MTIUS29l0OCtndI8tDiOgePkllquWbiDk0TFnAEqp2hWSxUyTafyfnkh+YUU8/ujsGb87R9U3QcvirK9DYGOLMjlXaXBtjiG+X92TuN8gJr0PAWQNvHNRCEhC5+8gK3dlWSE0urNHxMvOojuerEcm03AV4wyZCFij4xieR3BGKwhi6J1SxkLpc0RgOaTWmoTHGdse+ruZe4srk4e0lxaQgu60Xydy5aW4/dA0b7+WKS+r+b5Xq5YR39mWu/Hs/2WbTHR9Fhs5lotvlHgRZ4fIsK1RdgsMFWJ3X7USivTX91IX7jW+WEXLFMI4Smd3Q/GUPy2CsBsgzlZI7wLQEhU74paMjNPlNtH/O1bdC7/V9zBLt+dmJuycGHQjMFiOlFjpk4VF+qlWt4+U/6PiEebUuOoz1XVVYP6IgGFuDl8owFrEUE6gqQm53HXp31qhkL+gVXZ9KUFXDNtF+AMKrWlIa2YLfNooi9aUFXKiLmj4DI7AO0bdIEVxgkAiwVruBGT3VspRck3EotvoW8gSMH+dcrLTKgDm1n8H3cF+4UA7erDUJnxI94VxPMNSqdDhE052pZpvhxfurwEibq1w6IxyCpdCM=
